name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [timetable-data-updated]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: corepack enable
      - name: Clone timetable data
        env:
          PUBLIC_TIMETABLE_REPO: https://github.com/Jakob-Muel/neiphos2k26-timetable-data.git
        run: chmod +x ./clone-timetable-repo.sh && ./clone-timetable-repo.sh
      - run: yarn install --immutable
      - name: Build
        env:
          BASE_PATH: /neiphos2k26-timetable
          PUBLIC_TIMETABLE_REPO: https://github.com/Jakob-Muel/neiphos2k26-timetable-data.git
        run: yarn build
      - uses: actions/configure-pages@v5
        with:
          enablement: true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
